#!/bin/sh

if test -f .tarball-version
then
	v=`cat .tarball-version`
else
        v=`git describe --tags`
fi

# remove initial 'v'
v=`echo "$v" |sed 's/^v//'`

# for m4_esyscmd
echo "$v" | tr -d '\012'
